### ISSUE TITLE
Plugin Not working as intended

### ISSUE THREAD

**Issue by iLVOEWOCK** [cooldogepm/BedrockEconomy#104]
**Describe the bug**
Try running any sort of command on a local server and it will not send any feedback to the sender, only when the command has invalid arguments.

**To Reproduce**
1. Download plugin from [poggit](https://poggit.pmmp.io/p/BedrockEconomy/2.1.2)
2. Start lan server
3. run any command (e.g /balance, /setbalance)
4. No outcome unless a bad argument is provided.

**Expected behavior**
The response of each command. (self explantory, if i type /balance clearly i want to see my balance.)

**Screenshots**
not possible to screenshot nothing.. but i will add a video.

**OS and version (please complete the following information):**
 - Server OS: Windows 10
 - PocketMine-MP version: 5.4.2
 - Version: 2.1.2

**Additional context**
Video is too long to attach.
https://imgur.com/a/ybe0N2s

**Comment by cooldogedev** [comment]
Can you try disabling the other plugins and try it by itself?

**Comment by cooldogedev** [comment]
Try binary search, remove half of the plugins and see if the issue persists, if so repeat until you find the cause.

**Comment by iLVOEWOCK** [comment]
oh i figured it out, it was [FakePlayer](https://github.com/Muqsit/FakePlayer)
