### ISSUE TITLE
issuee with bankui

### ISSUE THREAD

**Issue by Kelvincleon1234** [cooldogepm/BedrockEconomy#129]
<html>
<body>
<h3 style="box-sizing: inherit; font-weight: 400; line-height: 48.18px; font-size: 2.92rem; margin: 1.94667rem 0px 1.168rem; color: rgba(0, 0, 0, 0.87); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Error information</h3><div class="card-panel red lighten-2 white-text z-depth-0" style="box-sizing: inherit; background-color: rgb(229, 115, 115) !important; color: rgb(255, 255, 255) !important; box-shadow: rgba(0, 0, 0, 0.14) 0px 2px 2px 0px, rgba(0, 0, 0, 0.12) 0px 3px 1px -2px, rgba(0, 0, 0, 0.2) 0px 1px 5px 0px; transition: box-shadow 0.25s ease 0s, -webkit-box-shadow 0.25s ease 0s; padding: 18px; margin: 0.5rem 0px 1rem; border-radius: 2px; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Warning: the<span> </span><strong style="box-sizing: inherit; font-weight: 500;">BedrockEconomy</strong><span> </span>plugin was directly involved in this crash. Please contact the plugin author.</div>
Thread: | Main
-- | --
cooldogedev\BedrockEconomy\api\version\BetaBEAPI::deduct(): Argument #2 ($balance) must be of type int, float given, called in phar:///home/kelvincleon590/bedrock/plugins/BankUI.phar/src/Electro/BankUI/BankUI.php on line 794
plugins/BedrockEconomy.phar/src/cooldogedev/BedrockEconomy/api/version/BetaBEAPI
#129
TypeError

</body>
</html>

when i type 100000000000000000000000000000 on the banks there issue with ur plugins economy the server is crashing i open logs and got this Warning: the BedrockEconomy plugin was directly involved in this crash. Please contact the plugin author.

**Comment by cooldogedev** [comment]
The max is [9,223,372,036,854,775,807 (9 quintillion)](https://github.com/cooldogepm/BedrockEconomy/blob/pm5/src/cooldogedev/BedrockEconomy/database/constant/Limits.php#L37)
