### ISSUE TITLE
Introduce labels

### ISSUE THREAD

**Issue by cooldogedev** [cooldogepm/BedrockEconomy#76]
**Is your feature request related to a problem? Please describe.**
Rather than storing the balance in a column we store it in a label-based json format, doing so will add more flexibility to implement new features such as the following https://github.com/cooldogedev/BedrockEconomy/issues/73, https://github.com/cooldogedev/BedrockEconomy/issues/69, https://github.com/cooldogedev/BedrockEconomy/issues/46

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SOF3** [comment]
why JSON format?

**Comment by cooldogedev** [comment]
> why JSON format?

So it can be parsed and updated by other code without having to implement a custom parser. E.g. directly updating players balances via a dashboard (from the backend)

**Comment by SOF3** [comment]
How is #69 related? Are you planning to store decimal base in a label?

**Comment by SOF3** [comment]
> > why JSON format?
> 
> So it can be parsed and updated by other code without having to implement a custom parser. E.g. directly updating players balances via a dashboard (from the backend)

so each label is a JSON object? Wouldn't that increase the difficulty of indexing?

What about two separate label types, one that is optimized for indexing, and one that is only used for storing metadata?

**Comment by ItzxDwi** [comment]
#90
