### ISSUE TITLE
Balance is set incorrectly

### ISSUE THREAD

**Issue by NhanAZ** [cooldogepm/BedrockEconomy#82]
**Describe the bug**
Balance is set incorrectly

**To Reproduce**
1. /setbalance Boo 0
2. /setbalance Boo -1 (This error occurs with all negative numbers)

**Expected behavior**
Boo's balance will be -1 or 0

**Screenshots**
![image](https://user-images.githubusercontent.com/60387689/178904302-637a5fca-1659-45ad-8ef9-4b2bcd0b1bb2.png)

**OS and version (please complete the following information):**
 - Server OS: [Windows 11]
 - PocketMine-MP version: [4.6.0]
 - Version [2.0.8]

**Additional context**
N/A

**Comment by cooldogedev** [comment]
This happens due to this [check](https://github.com/cooldogedev/BedrockEconomy/blob/main/src/cooldogedev/BedrockEconomy/command/admin/SetBalanceCommand.php#L72), bedrock economy supports unsigned integers only.
