### ISSUE TITLE
Add support for PM5

### ISSUE THREAD

**Issue by supercrafter333** [cooldogepm/BedrockEconomy#87]
Hello,
PM5 will be released on 1st march 2023. It would be good if developers can update and test their PM5 plugins with BedrockEconomy.
Please update BedrockEconomy for PM5.

**Comment by Astro-PM** [comment]
1 june

**Comment by ItzxDwi** [comment]
Any updates? @cooldogedev

**Comment by cooldogedev** [comment]
Available to download from [Poggit's dev builds](https://poggit.pmmp.io/ci/cooldogepm/BedrockEconomy/BedrockEconomy/dev:36)
