### ISSUE TITLE
No commands are working

### ISSUE THREAD

**Issue by trickalia** [cooldogepm/BedrockEconomy#93]
**Describe the bug**
can you please fix bedrockeconomy none of the commands are  working like /balance gives a output of nothing same when i add money

**To Reproduce**
1. Go to 'on text and put /balance or any other command'
2. Click on 'no value is showing back'

**Expected behavior**
to show my balance and to be able to add and remove money doing /addbalance player 10000 but nothing comes back.

**Screenshots**
i typed in and got nothing:
![image](https://github.com/cooldogepm/BedrockEconomy/assets/39748350/aff016ce-9e6b-4d89-8c20-33e900a009da)

**OS and version (please complete the following information):**
 - Server OS: [e.g. Windows 11]
 - PocketMine-MP version [5.0.1]

**Additional context**

**Comment by cooldogedev** [comment]
`/addbalane player 100000`
