### ISSUE TITLE
Crash when starting the Server

### ISSUE THREAD

**Issue by TwilightPhoenixX** [cooldogepm/BedrockEconomy#98]
When I start the Server they Server crashes

1. Download the plugin
2. put in plugin folder
3. Start Server
4. Login..... Error

![image](https://github.com/cooldogepm/BedrockEconomy/assets/139549920/c202df68-427d-429a-959c-0e58095a7a76)

**Comment by cooldogedev** [comment]
Fixed by https://github.com/cooldogepm/BedrockEconomy/commit/1429d03f24e6949b437f199f96c8bea4a7e42349
